import type { Product } from '@/types';

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Refrigerador FrostFree 400L',
    slug: 'refrigerador-frostfree-400l',
    description: 'Refrigerador moderno de acero inoxidable con dispensador de agua y tecnología FrostFree para evitar la acumulación de hielo.',
    price: 2499.99,
    imageUrl: 'https://picsum.photos/seed/101/800/1200',
    imageHint: 'refrigerator kitchen',
    category: 'large',
    specifications: {
      'Capacidad': '400 Litros',
      'Eficiencia Energética': 'A++',
      'Dimensiones (AlxAnxPr)': '185cm x 60cm x 65cm',
      'Tipo': 'Dos puertas',
      'Color': 'Acero Inoxidable',
    },
    warrantyPrice: 250,
    installationPrice: 150,
  },
  {
    id: 'prod_002',
    name: 'Lavadora Carga Frontal 8kg',
    slug: 'lavadora-carga-frontal-8kg',
    description: 'Lavadora de carga frontal con capacidad de 8kg, múltiples programas de lavado y motor inverter silencioso.',
    price: 1899.00,
    imageUrl: 'https://picsum.photos/seed/102/800/800',
    imageHint: 'washing machine',
    category: 'large',
    specifications: {
      'Capacidad de Lavado': '8 kg',
      'Velocidad de Centrifugado': '1400 RPM',
      'Eficiencia Energética': 'A+++',
      'Programas': '15',
      'Color': 'Blanco',
    },
    warrantyPrice: 190,
    installationPrice: 100,
  },
  {
    id: 'prod_003',
    name: 'Horno Microondas Grill 25L',
    slug: 'horno-microondas-grill-25l',
    description: 'Horno microondas de diseño elegante en color negro, con función grill y 25 litros de capacidad.',
    price: 599.50,
    imageUrl: 'https://picsum.photos/seed/103/800/600',
    imageHint: 'microwave oven',
    category: 'small',
    specifications: {
      'Capacidad': '25 Litros',
      'Potencia': '900W',
      'Función Grill': 'Sí, 1000W',
      'Niveles de Potencia': '5',
      'Color': 'Negro',
    },
    warrantyPrice: 60,
  },
  {
    id: 'prod_004',
    name: 'Smart TV 4K 65"',
    slug: 'smart-tv-4k-65',
    description: 'Televisor inteligente de 65 pulgadas con resolución 4K UHD, HDR y sistema operativo avanzado con tus apps favoritas.',
    price: 3200.00,
    imageUrl: 'https://picsum.photos/seed/104/1200/800',
    imageHint: 'smart tv',
    category: 'large',
    specifications: {
      'Tamaño de Pantalla': '65 pulgadas',
      'Resolución': '3840 x 2160 (4K UHD)',
      'Tecnología': 'LED',
      'Puertos HDMI': '3',
      'Smart OS': 'Sí',
    },
    warrantyPrice: 320,
    installationPrice: 200,
  },
  {
    id: 'prod_005',
    name: 'Cafetera de Goteo Programable',
    slug: 'cafetera-goteo-programable',
    description: 'Prepara el café perfecto cada mañana. Cafetera de goteo programable con jarra de vidrio y filtro permanente.',
    price: 250.00,
    imageUrl: 'https://picsum.photos/seed/105/800/1000',
    imageHint: 'coffee maker',
    category: 'small',
    specifications: {
      'Capacidad': '1.5 Litros (12 tazas)',
      'Programable': 'Sí, 24 horas',
      'Filtro': 'Permanente, lavable',
      'Función Mantener Caliente': 'Sí',
      'Color': 'Negro y Acero',
    },
    warrantyPrice: 25,
  },
  {
    id: 'prod_006',
    name: 'Licuadora de Alta Potencia',
    slug: 'licuadora-alta-potencia',
    description: 'Licuadora de alta velocidad ideal para smoothies, sopas y más. Con vaso de tritan resistente y cuchillas de acero.',
    price: 450.00,
    imageUrl: 'https://picsum.photos/seed/106/800/1000',
    imageHint: 'kitchen blender',
    category: 'small',
    specifications: {
      'Potencia': '1200W',
      'Capacidad del Vaso': '2 Litros',
      'Material del Vaso': 'Tritan (Libre de BPA)',
      'Velocidades': 'Variable + Pulso',
      'Color': 'Gris',
    },
    warrantyPrice: 45,
  },
];

export const getProductBySlug = (slug: string): Product | undefined => {
  return products.find((p) => p.slug === slug);
};
